### ISSUE TITLE
dist version

### ISSUE THREAD

**Issue by diasdavid** [diasdavid/js-peer-id#7]
@nginnever noticed that we the move to WebPack, we lost our minified dist version (the one that was present was from and earlier version). This is not urgent, but would you mind adding a script (npm script or gulp script) to make it available again?

Thank you!

**Comment by nginnever** [comment]
Sure! I wasn't aware that we had a dist for js-peer-id but I will work on adding an npm build script with browserify for it. Also I notice that none of our js-modules have dist scripts. I can go through as many as I can find and add them if you want. Will put on my TODO list.

**Comment by diasdavid** [comment]
At some point, I started adding to all of them (at the same time I added browser tests with tape and zuul), but yes, please, if you can help making everything well tests, specially on the browser, that will be a big boost! :D 

think js-libp2p + js-ipfs + utilities like js-multistream, js-multiaddr, js-multihashing, js-multihashes, etc

**Comment by nginnever** [comment]
See <a href="https://github.com/diasdavid/js-peer-id/commit/73b42ff2aa686ba7b6175ccf60a747b29f3e1e14">commit</a> 

We have a dist file now built with webpack that will run in the browser. The only problem is I had to use webpack since we have that conditional on ```require('buffer!./protobuf')``` for the node / browser env. Finding a way to get browserify to work with our webpack build is the current hold up. Others won't be able to use peer-id with their browserify projects without using webpack like we do. They would have to strip that conditional and build with brfs I AFAIK.

Let me know if you have any suggestions on this.

**Comment by diasdavid** [comment]
Dropping browserify support for now due to the node-forge issue is understandable, we can get it back once node-forge is properly modularized. Let's just make sure the docs on the README are up to date and inform the users that browserify doesn't work and why.

Note: Please don't commit to master, every contribution must go through the PR+CR route, this is crucial for the stability of the project. I've give push perms to you so that you can create branches on this repo and commit to other PRs without having to 'PR the PR'. I should have explained it to you probably, my bad, my apologies.

**Comment by nginnever** [comment]
No no my apologies, totally misread that. I thought giving me perm to the repo was because that commit was going to be to small for you to deal with or something. Thank you for clarifying and I will be sure to follow PR + CR even for the little things :D

**Comment by diasdavid** [comment]
We have now a dist version \o/  :D
